---
name: Setup uv and handle its cache
description: Downloads and installs the Python uv packaging manager and handles its cache.
author: Hynek Schlawack
branding:
  icon: package
  color: purple


runs:
  using: composite

  steps:
  - name: Install uv
    run: |
      curl -LsSf https://astral.sh/uv/install.sh
      | sh --no-modify-path --verbose
    shell: bash

  - name: Find uv cache
    run: echo "UV_CACHE=$(uv cache dir)" >>$GITHUB_ENV
    shell: bash

  - name: Load uv cache
    uses: actions/cache@v4
    with:
      path: ${{ env.UV_CACHE }}
      key: ${{ runner.os }}-uv
